name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t shinyapp .
      - name: Run Docker container
        run: |
          docker run \
            -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }} \
            -e SHINYAPPS_TOKEN=${{ secrets.SHINYAPPS_TOKEN }} \
            -e SHINYAPPS_SECRET=${{ secrets.SHINYAPPS_SECRET }} \
            -e SHINY_APP_NAME=${{ secrets.SHINY_APP_NAME }} \
            shinyapp
